### ISSUE TITLE
[BUG] Selection checkmark

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-fundamentals#14]
**Describe the bug**
When on mobile the selection checkmark is rendered over the text.

**To Reproduce**
1. Go to mobile view
2. Click on one of the answers
3. See error

**Expected behavior**
The checkmark should be rendered on the left side of the text, like it is on desktop.

**Screenshots**
![image](https://user-images.githubusercontent.com/9199763/222954445-a376eb54-c223-4d23-9f71-9dc61655821d.png)

**Comment by jSunpayco** [comment]
You can try using padding instead of margin for the choices
`<span className="pl-7`
instead of
`<span className="sm:ml-3 md:ml-7`

**Comment by eduardconstantin** [comment]
Yes, that could work
