### ISSUE TITLE
[Feature] Create home page

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-fundamentals#18]
**Is your feature request related to a problem? Please describe.**
The application needs a home page. In the future the application will have an exam mode.

**Describe the solution you'd like**
A new home page for the application with two buttons for selecting one of the modes.

**Additional context**
I created a figma design file [here](https://www.figma.com/file/ckNeex3dSR7Y32bPfJHiQQ/Azure-Fundamentals?node-id=0%3A1&t=ylV8yUc5OB4Z5XvV-1)
![image](https://user-images.githubusercontent.com/9199763/224372648-a26d2f2a-4b2f-45c5-9fdf-435ac19c14a3.png)

**Comment by milafreckled** [comment]
@eduardconstantin I have a few questions: 
1. Is this task only about design, or should some functions also be integrated into the app?
3. Are only Tailwind classes allowed or desirable to complete it?
Thank you in advance for your answer.

**Comment by eduardconstantin** [comment]
> @eduardconstantin I have a few questions:
> 
> 1. Is this task only about design, or should some functions also be integrated into the app?
> 2. Are only Tailwind classes allowed or desirable to complete it?
>    Thank you in advance for your answer.

1. It also needs to have some functionality on the buttons like when you press on **practice mode** it will redirect to the current page that is in the app. When pressing on **exam mode** it should redirect to an empty page for now.
2. Yes, the design should be made only using tailwind classes that are found [here](https://tailwindcss.com/docs/flex-basis).
Would you like to work on this issue?

**Comment by milafreckled** [comment]
@eduardconstantin yes, I would like to

**Comment by eduardconstantin** [comment]
Great! Make sure to make a new branch from the dev branch
