### ISSUE TITLE
[BUG] Question text not readable enough

### ISSUE THREAD

**Issue by magmukendi** [eduardconstantin/azure-fundamentals#21]
**Describe the bug**
The question font size is too small on desktop. 

**To Reproduce**
1. Open the the URL.

**Expected behavior**
The question font text should be big enough to be readable on desktop.

**Screenshots**
![image](https://user-images.githubusercontent.com/64711820/229949376-fe80af86-5d64-449b-bb73-3754e4a3d3a8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version 111.0.1661.62

**Additional context**

**Comment by LeGrandMAG** [comment]
I would be great to work on this issue.

**Comment by eduardconstantin** [comment]
The text is generated using vercel og, on the back end. You should keep in mind that the text should be visible also on the mobile view.

**Comment by SAGARSINGH-1** [comment]
please assign me this issue

**Comment by eduardconstantin** [comment]
@SAGARSINGH-1 sure, but I would like to replace the Image component with simple text that can't be selected.

**Comment by SAGARSINGH-1** [comment]
@eduardconstantin can you check my PR first.

**Comment by SAGARSINGH-1** [comment]
@eduardconstantin  Or can you help me with that error why it can't fetch questions : 
<img width="633" alt="image" src="https://github.com/eduardconstantin/azure-fundamentals/assets/81561733/e4fa4a4c-54aa-4415-8ee9-8cc4902118fa">

**Comment by eduardconstantin** [comment]
where is this happening? I checked the practice mode and it looks fine

**Comment by SAGARSINGH-1** [comment]
In locally setup

**Comment by eduardconstantin** [comment]
it works fine for me
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/9199763/05f85fff-85ce-4f18-b412-6d969bf23899)

**Comment by SAGARSINGH-1** [comment]
Ohh, Alright then
