### ISSUE TITLE
[BUG] Text of the Answer choice not readable

### ISSUE THREAD

**Issue by LeGrandMAG** [eduardconstantin/azure-fundamentals#22]
**Describe the bug**
The text contained in the answer options button are not readable enought due to the color of their font.

**To Reproduce**
Open the website

**Expected behavior**
User should be able to read the text.

**Screenshots**
![image](https://user-images.githubusercontent.com/64711820/229949865-d151b3f1-4e9e-4da0-8e2f-a4e06b338187.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version 111.0.1661.62

**Additional context**

**Comment by eduardconstantin** [comment]
Interesting find, do you have dark mode enabled?
I checked on edge and looks fine.
![image](https://user-images.githubusercontent.com/9199763/230124194-1bf312d3-552e-4bf3-b002-90d1cf28ac00.png)

**Comment by LeGrandMAG** [comment]
No, I don't have darkmode activated. :( It looks the same on my Chrome and Edge
