### ISSUE TITLE
[Feature] Submitting Answer/Revealing answer

### ISSUE THREAD

**Issue by LeGrandMAG** [eduardconstantin/azure-fundamentals#23]
**Is your feature request related to a problem? Please describe.**
Currently there are only two button, for going to the next question and revealing the correct answer. But it would be better if the user can submit there answer and discover whether it is the correct one.

**Describe the solution you'd like**
Instead of having the reveal answer button, it would be better to have a Submit button, that will check whether the answer the user submitted is correct and display the correct answer.

**Comment by LeGrandMAG** [comment]
I would be interested in working on this issue.

**Comment by eduardconstantin** [comment]
Sorry but I don't really understand, from what you explained the reveal answer button does the same thing as the submit answer button.

**Comment by LeGrandMAG** [comment]
I checked again. But the Reveal button does not handle multiple scenarios.

**In case the user choose the correct answer**, clicking reveal answer highlights the correct answer in green. What can be improved: Should show that the other answers are incorrect by highlighting them in red.

In case the user chooses the wrong answer, clicking reveal answer, does not do anything, no change in the UI. What can be improved: Clicking the wrong answer should highlight the correct answer in green and the wrong answers in red.

In case the user chooses nothing, clicking reveal answer, makes all the answer options inactive. What can be improved: Should make Reveal answer inactive until one answer option is selected.

**Comment by eduardconstantin** [comment]
I don't want to clutter the user with too much visual information, I think is pretty understandable that if the correct answer is highlighted in green the remaining answers are wrong. 
For the third case I wanted to give the user the option to see the correct answers without selecting anything. This won't be available in the upcoming exam mode, where the correct answers will be visible at the end of the quiz.

One improvement that I could see here is to let the user see the selected option after the reveal. This could be done by highlighting the user selection with an outline instead using a border.

**Comment by eduardconstantin** [comment]
@LeGrandMAG can you check the application again, I think you were not able to see the right behaviour because of dark mode.
