### ISSUE TITLE
[Feature] Page selection button component

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-fundamentals#31]
Is your feature request related to a problem? Please describe.
Currently, the page selection buttons from the home page are hardcoded.

Describe the solution you'd like
A new page button component added to the library that uses Tailwind variants for customization.
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/9199763/e6d1bb4e-aafb-4e61-a249-adf0a1c3569d)

Additional context
[Class Variance Authority](https://github.com/joe-bell/cva) can be used to create the tailwind variants.
Check [button component](../blob/main//components/Button.tsx)

**Comment by Lucif3r-in** [comment]
Hey @eduardconstantin Can I work on this?

**Comment by Lucif3r-in** [comment]
For some reason I am not able to make a PR, don't know why so unassigned myself
