### ISSUE TITLE
[Feature] Jump to question # - and/or randomize

### ISSUE THREAD

**Issue by wcrisafu** [eduardconstantin/azure-fundamentals#44]
If I close the browser and reopen it, I have to restart from question #1. If the questions were randomized it would not matter but having to getting back to a question, may take a few hundred clicks.

**Comment by eduardconstantin** [comment]
good idea, I was thinking about that too but I don't know where to add it on the page

**Comment by wcrisafu** [comment]
I was thinking that the first label (the one with the incremental #) could become a text field and it someone enters a number and press the enter key, it would jump to the question.

**Comment by eduardconstantin** [comment]
Created this design for solving this issue -> [Figma file](https://www.figma.com/file/ckNeex3dSR7Y32bPfJHiQQ/Azure-Fundamentals?type=design&node-id=26%3A86&mode=design&t=TP3EUUB1KvdeKGwO-1)
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/9199763/d3c7143d-6289-4de2-8027-bb44cf4bc3bc)
