### ISSUE TITLE
[BUG] Text overflows

### ISSUE THREAD

**Issue by masterHAWK99** [eduardconstantin/azure-fundamentals#45]
**Describe the bug**
Text overflows on certain window width.

**To Reproduce**
Just make your browser window smaller. Occurs between 938px and 639px.

**Screenshots**
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/60447475/ab1be7bd-3b98-494e-b168-b611239864b7)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome, firefox
 - Version 114

**Comment by eduardconstantin** [comment]
nice find! I checked your pr and you worked on main branch, could you switch to dev and pull the latest changes?
