### ISSUE TITLE
[Feature] Exam Mode Quiz UI

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-fundamentals#60]
**Is your feature request related to a problem? Please describe.**
As a student preparing for the Azure Fundamentals certification, I value a user-friendly and engaging interface when I enter exam mode. Currently the exam mode only has the intro screen, the next one is the quiz itself. 

**Describe the solution you'd like**
To enhance the exam experience, we need to implement the UI for the exam mode that includes the following components:
 - **Question Display:** Each question should be presented clearly and legibly. The practice mode uses Next image, for exam mode let's keep it simple text that can't be selected.
 - **Answer Selection:** I should be able to select my answer choice by clicking the option bar. The selected choice should be visually indicated.
 - **Timer:** A timer displaying the remaining time in "mm:ss" format should be prominently visible throughout the exam in the top right corner. The timer should start automatically when the quiz appears and stop when the time limit is reached or the user has answered the final question.
- **Progress Indicator:** An indicator showing the progress, such as "X of 50," should help keep track of the progress. It should be positioned in the top left corner and it should update dynamically as the user move through the questions.
- **Next Question Button:** A clearly labeled "Next Question" button should be provided for the user to move to the next question and save the selected answer/s. The button should be disabled if no answer is selected.
- **Skip Question Button:** A clearly labeled "Skip Question" button should be provided for the user to move to the next question without selecting any answer. The skipped questions should be visible at the end of the exam.

**Additional context**
The practice mode already has the quiz component made, which it's a good starting point. 

![image](https://github.com/eduardconstantin/azure-fundamentals/assets/9199763/4a9e0703-f5dd-4358-87c2-eefe43123f14)
You can find the link to figma file [here.](https://www.figma.com/file/ckNeex3dSR7Y32bPfJHiQQ/Azure-Fundamentals?type=design&node-id=417%3A10&mode=design&t=iEDVcKy710touMia-1)

**Comment by masterHAWK99** [comment]
I started working on this.
