### ISSUE TITLE
[Feature] Validate User Answers and Calculate Results

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-fundamentals#62]
**Is your feature request related to a problem? Please describe.**
As a student preparing for the Azure Fundamentals certification, I place great importance on receiving accurate feedback on my exam performance. In the exam mode, after completing the questions within the allotted time, the system should validate the user's answers and calculate the points.

**Describe the solution you'd like**
Probably the best solution for this is to create a custom hook, but I am open to better suggestions.
The total points of all the questions should add up to 100 and it should take in consideration that there are also questions with multiple answers.

**Comment by Bazi99** [comment]
@eduardconstantin I am interested in it :)

**Comment by eduardconstantin** [comment]
Great! I assigned you, please make sure you create a new branch from the dev branch

**Comment by eduardconstantin** [comment]
@masterHAWK99 has implemented this feature in this PR #65
