### ISSUE TITLE
[Feature] Exam mode completion UI

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-fundamentals#63]
**Is your feature request related to a problem? Please describe.**
As a student preparing for the Azure Fundamentals certification, I value a user-friendly and engaging interface when I finish the exam mode. This is the last screen in the exam mode.

**Describe the solution you'd like**
To enhance the exam experience, the completion screen need to be implemented which includes the following components:
- **Exam status:** A text that show if the exam has been passed or not. The color of the text should be green if the exam is passed and red if not.
- **Points:** A text showing the number of points the user has made "X/100". Same as the exam status the points should be colored green if the exam has been passed or red if not.
- **Completion message:** A text showing the user a congratulatory message and the amount of time it took to pass the exam. If the exam is failed it should tell the user the minimum amount of points needed to pass the exam.
- **Retake Exam Button:** A clearly labeled "Retake exam" button should be provided for the user to let him retake the exam with new random questions.

**Additional context**

![image](https://github.com/eduardconstantin/azure-fundamentals/assets/9199763/851173b7-971e-4b76-a6d7-7bfbe0983dbf)
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/9199763/f784aad9-64f0-4501-86ba-b2d7b85b8161)

You can find the link to figma file [here.](https://www.figma.com/file/ckNeex3dSR7Y32bPfJHiQQ/Azure-Fundamentals?type=design&node-id=417%3A10&mode=design&t=iEDVcKy710touMia-1)

**Comment by SAGARSINGH-1** [comment]
here i done the UI : 
<img width="958" alt="image" src="https://github.com/eduardconstantin/azure-fundamentals/assets/81561733/d1dab7a2-d7c7-4a6c-98d3-b3b7e9b00308">

**Comment by eduardconstantin** [comment]
This is mostly a design implementation task, but you need to make it look exactly like the figma design.
You can find the component for the button and some layout for the texts in the project and use them.
Also you will have to wait for @Bazi99 to finish the feature in order to get the necessary data from him.

**Comment by eduardconstantin** [comment]
it seems that @masterHAWK99 has implemented the design and the functionality in his PR #65

**Comment by SAGARSINGH-1** [comment]
@eduardconstantin then I have to create result UI or not?

**Comment by SAGARSINGH-1** [comment]
Is he completed the UI or I have to?

**Comment by eduardconstantin** [comment]
Let's wait to merge his pr and you can fix the UI if is necessary.

**Comment by eduardconstantin** [comment]
@SAGARSINGH-1 I think you can take a look at the completion UI now, make sure it looks like in the design file

**Comment by SAGARSINGH-1** [comment]
First, let me start by saying that I appreciate the effort put into it, and it looks great overall. However, I've noticed a few areas where we can make some improvements to align the design with our Figma reference and enhance the user experience.

1. **Paragraph Missing**

2. **Number of Questions Missing**

3. **Time Information Missing**

![image](https://github.com/eduardconstantin/azure-fundamentals/assets/81561733/72529eec-ba03-4974-ba94-18a3e8370d03)

**Comment by SAGARSINGH-1** [comment]
Should I create an issue for improving it.

**Comment by eduardconstantin** [comment]
you can create a PR, but make sure to pull the latest changes from the dev branch

**Comment by SAGARSINGH-1** [comment]
Ok.

**Comment by SAGARSINGH-1** [comment]
Creating a PR with that UI let me know if you need any changes: 

<img width="933" alt="image" src="https://github.com/eduardconstantin/azure-fundamentals/assets/81561733/ac09daa4-ada8-4f35-a901-56e862736136">
