### ISSUE TITLE
[BUG] Questions index should start from 1

### ISSUE THREAD

**Issue by masterHAWK99** [eduardconstantin/azure-fundamentals#66]
**Describe the bug**
In Practice or Exam mode questions index starts from 0

**To Reproduce**
1. Go to Practice or Exam mode
2. In Practice you can see it starts from 0, in Exam after "Begin exam" is clicked, on the right side is "0/30"

**Expected behavior**
Questions index should start from 1, not 0

**Screenshots**
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/60447475/6c96ef42-f842-4553-8bef-eafb21aec3b7)
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/60447475/8c934f77-7491-4b5d-9de0-597ccc69ef33)

**Comment by weedertree** [comment]
could you please assign me with this issue?

**Comment by eduardconstantin** [comment]
@weedertree did you manage to find a solution for this bug?

**Comment by a6ar55** [comment]
hey ,I would like to work on it.

**Comment by taran1326** [comment]
Hey can I work on this issue? can you assign me this issue ?

**Comment by taran1326** [comment]
Hey @eduardconstantin @masterHAWK99  I am facing an issue here in the exam mode section , i can spot the page as in your screenshots , instead this is coming

![image](https://github.com/eduardconstantin/azure-fundamentals/assets/75477822/47450bb7-6290-4c09-8de5-d222d53e1442)

i there something that I am missing in the settup?

**Comment by masterHAWK99** [comment]
@taran1326 Make sure you are on dev branch and have newest changes.

**Comment by taran1326** [comment]
hey @masterHAWK99  I am facing little difficulty here , can you help me with suitable commands to set up the project ?

**Comment by eduardconstantin** [comment]
@taran1326 I think you should take one issue at a time

**Comment by taran1326** [comment]
sure !

**Comment by eduardconstantin** [comment]
finish this one first https://github.com/eduardconstantin/Regenerator/issues/37 and if no one takes this one you can do this too

**Comment by sushma1031** [comment]
Hello, I'd like to work on this, could you please assign it to me?

**Comment by sushma1031** [comment]
@eduardconstantin The total number of questions are 31, but it's being displayed as 30. Can you please tell me why?

**Comment by eduardconstantin** [comment]
@sushma1031 the questions are randomly selected in `questionsDataSource`
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/9199763/f2fc18f4-93da-4ba7-9ebe-c9135fc468b5)

**Comment by sushma1031** [comment]
In `exam/index.tsx` :
```
 const { loading, error, data } = useQuery(questionsQuery, {
    variables: { range: 31 },
  });
```
Since the range is being passed as 31 here, questions from indices 0 to 30 are being fetched, resulting in 31 questions. So in order to get 30 questions, shall I change the range to 30?

**Comment by eduardconstantin** [comment]
yes, let's keep it to 30 for now

**Comment by masterHAWK99** [comment]
@eduardconstantin but questions index start from 0, not 1, that's why we need to fetch 31.

**Comment by eduardconstantin** [comment]
> @sushma1031 the questions are randomly selected in `questionsDataSource` ![image](https://user-images.githubusercontent.com/9199763/277172352-f2fc18f4-93da-4ba7-9ebe-c9135fc468b5.png) I use the slice() method to get the first 30 questions, so I guess it should be `range+1` in here to match the fetched questions

@masterHAWK99 I assume he changed the random questions data source

**Comment by sushma1031** [comment]
> @eduardconstantin but questions index start from 0, not 1, that's why we need to fetch 31.

From the MDN docs,
> The slice() method of [Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) instances returns a [shallow copy](https://developer.mozilla.org/en-US/docs/Glossary/Shallow_copy) of a portion of an array into a new array object selected from start to end (end not included) where start and end represent the index of items in that array.

So I think `slice(0, 30)` will return 30 values, from indices 0 to 29.
