### ISSUE TITLE
[Feature] Add questions counter

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-fundamentals#7]
**Is your feature request related to a problem? Please describe.**
Currently the application has nothing to show how many questions the user has answered.
A counter could be useful.

**Describe the solution you'd like**
Add a counter inside the form, above the question. (eg. 1/480)

![image](https://user-images.githubusercontent.com/9199763/222954295-7f507912-d7be-4865-9dfd-5118045e9714.png)

**Comment by Lucif3r-in** [comment]
Hello @eduardconstantin , Can I work on it?

**Comment by eduardconstantin** [comment]
Hello! Yes, it still is. I'll assign you

**Comment by Lucif3r-in** [comment]
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/85403534/e1eb020f-50bc-4ba2-adf1-62097bfe767f)
 
Is this ok @eduardconstantin ?

**Comment by eduardconstantin** [comment]
You have a photo in the first post. It should show the total no of answered questions/total number of questions

**Comment by eduardconstantin** [comment]
ha, right, you don't have access to the database. Just put 480 and I'll update it.

**Comment by Lucif3r-in** [comment]
> ha, right, you don't have access to the database. Just put 480 and I'll update it.

Oh! Got it raising the PR!
