### ISSUE TITLE
[BUG] Question answer selection

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-fundamentals#70]
**Describe the bug**
Currently the exam mode has a bug. When I select the first answer and click next question the first answer remains selected also for the next question.

**To Reproduce**
1. Go to Exam Mode
2. Click on Begin Exam
3. Click on first answer
4. Click on Next Question
5. See error -> first answer remains selected

**Expected behavior**
After I press Next Question no answer should be selected.

**Screenshots**
First question with first answer selected by the user
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/9199763/b06df87e-025a-461d-8325-678a18534887)
Second question with the first answer selected by default
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/9199763/1817ecf8-4f96-4f6f-9560-0caf3bc6d39e)

**Comment by Vedu1996** [comment]
Hey @eduardconstantin , I'd like to pick this up

**Comment by Vedu1996** [comment]
Hey @eduardconstantin , I figured out the fix for this but I see that the exam mode has a "Coming Soon" banner now. Do we want to archive this issue?

**Comment by masterHAWK99** [comment]
> Hey @eduardconstantin , I figured out the fix for this but I see that the exam mode has a "Coming Soon" banner now. Do we want to archive this issue?

Are you sure you're on dev branch and have the newest changes?

**Comment by Vedu1996** [comment]
Sure, will check, thanks
