### ISSUE TITLE
[BUG] The text is overflowing

### ISSUE THREAD

**Issue by masterHAWK99** [eduardconstantin/azure-fundamentals#76]
**Describe the bug**
The text is overflowing the boxes on large screens.

**To Reproduce**
1. Go to home page
2. Resize browser window horizontally to min. 2500px

**Expected behavior**
Text should stay in the same position.

**Screenshots**
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/60447475/8706cf0d-acd3-4a51-8366-5bd2b60814ae)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [latest]

**Comment by NewtonFernandis** [comment]
HI @masterHAWK99, I will work on this please assign this issue to me.

**Comment by NewtonFernandis** [comment]
@eduardconstantin Please review the PR and let me know if it needs anything.
