### ISSUE TITLE
[BUG] Error in console

### ISSUE THREAD

**Issue by masterHAWK99** [eduardconstantin/azure-fundamentals#77]
**Describe the bug**
Error related to quiz form appears in console

**To Reproduce**
1. Go to Practice Mode
2. See error in console

**Expected behavior**
No error

**Screenshots**
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/60447475/bca33143-e32f-477c-8159-12fa84375ae6)

**Comment by raviikushh** [comment]
It's working now. I've checked in localhost too.

**Comment by eduardconstantin** [comment]
Still there
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/9199763/b037979f-7b09-49ab-bcb8-82b377439123)

**Comment by taran1326** [comment]
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/75477822/1eb49929-4eaf-46ae-9ad6-f409de7f75fb)


hey why is this issue coming , was this coming before or I missed something while setting up project
to reporoduce:-
git clone
npm install
npm run dev

**Comment by eduardconstantin** [comment]
hm, that's strange, are you on the dev branch?
