### ISSUE TITLE
[BUG] Skip Question button functionality

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-fundamentals#81]
**Describe the bug**
In the exam mode the `Skip Question` button is not working properly

**To Reproduce**
1. Click on Exam Mode
2. Click on Begin Exam
3. Click on Skip Question until no more questions left

**Expected behavior**
When the user clicks on the Skip Question button, the current question should be added to a queue of skipped questions. 
The questions from the queue should be showed to the user after all the questions from the initial queue has been answered.
The exam should not end until the user has answered all the questions, including the ones in the queue, or the time limit has expired.

**Comment by Amnish04** [comment]
Hi, I was trying to reproduce the bug. But when I click on `Begin Exam` on the deployed link, I get the following screen.

![image](https://github.com/eduardconstantin/azure-fundamentals/assets/78865303/c1ccbccb-cac3-4df0-9153-00fcbfb4e702)

**Comment by eduardconstantin** [comment]
@Amnish04 you need to be on the dev branch

**Comment by Amnish04** [comment]
@eduardconstantin I can see it now, thanks for clarifying. Is it okay if I try to work on this one?

**Comment by eduardconstantin** [comment]
you're welcome! give it a try!
