### ISSUE TITLE
[BUG] Back button appears for the first question

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-fundamentals#85]
**Describe the bug**
In practice mode, when I click reveal answer for the first questions the back button appears.

**To Reproduce**
1. Go to Practice mode
2. Click on Reveal Answer
4. See bug

**Expected behavior**
The back button should appear from second question and above if the reveal answer button is pressed

**Screenshots**
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/9199763/25d8dc81-9838-4e66-9c3c-04a9c338544a)

**Comment by adripo** [comment]
Hi, I would like to work on this issue. Can I be assigned please?
