### ISSUE TITLE
[BUG] Reveal answer remains selected

### ISSUE THREAD

**Issue by eduardconstantin** [eduardconstantin/azure-fundamentals#86]
**Describe the bug**
In practice mode, if I press reveal answer button and I change the question number at the top of the page the option remains selected for all the questions.

**To Reproduce**
1. Go to Practice mode
2. Click on Reveal Answer
3. Change question number at the top of the page

**Expected behavior**
When the question changes no option should be selected or revealed

**Comment by adripo** [comment]
Hi, I would like to work on this issue too. Thank you.
