### ISSUE TITLE
[BUG] On the result screen, should be time taken to complete

### ISSUE THREAD

**Issue by masterHAWK99** [eduardconstantin/azure-fundamentals#90]
**Describe the bug**
When the user ends a test in Exam Mode, the congratulation text on the end screen displays the remaining time instead of the time taken to complete the test.

**To Reproduce**
1. Go to 'Exam Mode'
2. Click on 'Begin'
3. Answer questions
4. See end screen

**Expected behavior**
On the end screen, the congratulatory text should include the time taken to complete test.

**Screenshots**
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/60447475/ded083da-2a3b-4f42-ad69-b1bfdd5e8a01)

**Comment by eduardconstantin** [comment]
ah, yes, good catch, also the text should be on two rows

**Comment by RKOsvk** [comment]
Hello, can you assigne me for this issue?

**Comment by RKOsvk** [comment]
I can not reproduce bug because i get only this screen. Is there any further steps
![image](https://github.com/eduardconstantin/azure-fundamentals/assets/67868821/07e90f96-59e4-4115-852b-82c402d0494c)

**Comment by masterHAWK99** [comment]
Switch to dev branch

**Comment by eduardconstantin** [comment]
People are really not used to work on dev branches
