### ISSUE TITLE
[BUG] Update the answered question count when `Next` button is clicked.

### ISSUE THREAD

**Issue by Amnish04** [eduardconstantin/azure-fundamentals#91]
**Describe the bug**
Currently, the answered question count updates whenever a user selects an option.

**To Reproduce**
1. Click `Begin Exam`
2. Select an option
3. Notice the `answered questions` count updates.

**Expected behavior**
The selection should happen only when the user clicks on the `Next`  button.

**Comment by eduardconstantin** [comment]
@RKOsvk now you can do this too

**Comment by RKOsvk** [comment]
can you assigne me for this? i alreade solved it
